version: "3.2"
services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: mini_risk_manager_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432